### ISSUE TITLE
"Error: Value for a (-53.4484) must be between -52 and 100"

### ISSUE THREAD

**Issue by Pomax** [garex/nodejs-color-difference#8]
`cd.compare("#291510","#41a81c")` throws the subject's error. No idea why, there's nothing special about those two colours

**Comment by garex** [comment]
Ok. This can be solved more easily and covered by tests. tnx

**Comment by garex** [comment]
Possibly related: https://github.com/meyer/nodejs-color-model/commit/ed9f046e679a3f605a464031c3cc3b1996d88ec9

Incorrectly choosen limits.

**Comment by garex** [comment]
fixed in color-model. update it to 0.2.2
